//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roughProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDataTable
    {
        public EventDataTable()
        {
            this.TimeStoringTables = new HashSet<TimeStoringTable>();
        }
    
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string EventDetails { get; set; }
    
        public virtual ICollection<TimeStoringTable> TimeStoringTables { get; set; }
    }
}
