//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roughProj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testModelContext : DbContext
    {
        public testModelContext()
            : base("name=testModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EventDataTable> EventDataTables { get; set; }
        public DbSet<testingTable> testingTables { get; set; }
        public DbSet<TimeStoringTable> TimeStoringTables { get; set; }
    }
}
