//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roughProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class testingTable
    {
        public int testingTableId { get; set; }
        public Nullable<System.DateTime> initialTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    }
}
