//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roughProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeStoringTable
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public Nullable<System.DateTime> EventStartTime { get; set; }
        public Nullable<System.DateTime> EventStopTime { get; set; }
    
        public virtual EventDataTable EventDataTable { get; set; }
    }
}
